services:
  api:
    build: { context: ../.., dockerfile: infra/docker/dev.Dockerfile }
    command: ['yarn', 'workspace', '@nft-marketplace/api', 'dev']
    working_dir: /workspace
    volumes:
      - ../..:/workspace
      - dev-node-modules:/workspace/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: apps/api/package.json
        - action: rebuild
          path: packages

  workers:
    build: { context: ../.., dockerfile: infra/docker/dev.Dockerfile }
    command: ['yarn', 'workspace', '@nft-marketplace/workers', 'dev']
    working_dir: /workspace
    volumes:
      - ../..:/workspace
      - dev-node-modules:/workspace/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: apps/workers/package.json
        - action: rebuild
          path: packages

  indexer:
    build: { context: ../.., dockerfile: infra/docker/dev.Dockerfile }
    command: ['yarn', 'workspace', '@nft-marketplace/indexer', 'dev']
    working_dir: /workspace
    volumes:
      - ../..:/workspace
      - dev-node-modules:/workspace/node_modules
      - dev-indexer-cache:/workspace/apps/indexer/.ponder
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: apps/indexer/package.json
        - action: rebuild
          path: packages

  web:
    build: { context: ../.., dockerfile: infra/docker/dev.Dockerfile }
    command: ['yarn', 'workspace', '@nft-marketplace/web', 'dev']
    working_dir: /workspace
    volumes:
      - ../..:/workspace
      - dev-node-modules:/workspace/node_modules
      - dev-next-cache:/workspace/apps/web/.next
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: apps/web/package.json
        - action: rebuild
          path: packages

volumes:
  dev-node-modules:
  dev-indexer-cache:
  dev-next-cache:
