import React from 'react';
export const WalletState = { DISCONNECTED: 'disconnected', CONNECTING: 'connecting', CONNECTED: 'connected', WRONG_NETWORK: 'wrong-network', REJECTED: 'rejected', SIGNING: 'signing' } as const;
export const TransactionState = { INTENT: 'intent', PENDING: 'pending', SUBMITTED: 'submitted', CONFIRMED: 'confirmed', FAILED: 'failed', EXPIRED: 'expired' } as const;
export type WalletState = typeof WalletState[keyof typeof WalletState]; export type TransactionState = typeof TransactionState[keyof typeof TransactionState];
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> { variant?: 'primary' | 'secondary'; }
export function Button({ variant = 'primary', children, ...props }: ButtonProps) { return <button className="nft-button" data-variant={variant} {...props}>{children}</button>; }
export function Stack({ children, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className="nft-stack" {...props}>{children}</div>; }
export function Grid({ children, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className="nft-grid" {...props}>{children}</div>; }
export interface FieldProps { label: string; error?: string; id?: string; children: React.ReactNode; }
export function Field({ label, error, id, children }: FieldProps) { return <label className="nft-ui nft-stack" htmlFor={id}><span>{label}</span>{children}{error ? <span className="nft-status" data-tone="danger" role="alert">{error}</span> : null}</label>; }
export function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input className="nft-input" {...props} />; }
export function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className="nft-select" {...props} />; }
export function Form({ children, onSubmit, ...props }: React.FormHTMLAttributes<HTMLFormElement>) { return <form className="nft-ui nft-stack" onSubmit={onSubmit} {...props}>{children}</form>; }
export interface TableColumn<T> { key: string; label: string; render?: (row: T) => React.ReactNode; } export interface TableProps<T> { columns: TableColumn<T>[]; rows: T[]; getRowKey?: (row: T, index: number) => React.Key; }
export function Table<T>({ columns, rows, getRowKey = (_, index) => index }: TableProps<T>) { return <div role="region" aria-label="Data table" style={{ overflowX: 'auto' }}><table className="nft-ui"><thead><tr>{columns.map((column) => <th key={column.key} scope="col">{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={getRowKey(row, index)}>{columns.map((column) => <td key={column.key}>{column.render ? column.render(row) : String((row as Record<string, unknown>)[column.key] ?? '')}</td>)}</tr>)}</tbody></table></div>; }
export interface GalleryProps<T> { items: T[]; renderItem: (item: T) => React.ReactNode; getKey?: (item: T) => React.Key; }
export function Gallery<T>({ items, renderItem, getKey = (item) => (item as { id?: React.Key }).id ?? String(item) }: GalleryProps<T>) { return <div className="nft-grid" aria-label="Gallery">{items.map((item) => <article className="nft-card" key={getKey(item)}>{renderItem(item)}</article>)}</div>; }
export function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="nft-card"><div className="nft-card__body"><h3>{title}</h3>{children}</div></section>; }
const walletLabels: Record<WalletState, string> = { disconnected: 'Connect wallet', connecting: 'Connecting wallet', connected: 'Wallet connected', 'wrong-network': 'Switch network', rejected: 'Connection rejected', signing: 'Confirm signature' };
export function WalletStatus({ state, onAction }: { state: WalletState; onAction?: () => void }) { const actionable = state === WalletState.DISCONNECTED || state === WalletState.WRONG_NETWORK || state === WalletState.REJECTED; return <div className="nft-ui" role="status" aria-live="polite"><span>{walletLabels[state]}</span>{actionable ? <Button onClick={onAction}>{walletLabels[state]}</Button> : null}</div>; }
const txLabels: Record<TransactionState, string> = { intent: 'Transaction ready', pending: 'Waiting for wallet', submitted: 'Transaction submitted', confirmed: 'Transaction confirmed', failed: 'Transaction failed', expired: 'Transaction expired' };
export function TransactionStatus({ state, error }: { state: TransactionState; error?: string }) { return <div className="nft-ui nft-status" data-tone={state === TransactionState.FAILED ? 'danger' : 'neutral'} role="status" aria-live="polite"><strong>{txLabels[state]}</strong>{error ? <span role="alert">{error}</span> : null}</div>; }
export function Responsive({ children, as: Element = 'div', ...props }: { children: React.ReactNode; as?: keyof JSX.IntrinsicElements } & Record<string, unknown>) { return <Element className="nft-ui" {...props}>{children}</Element>; }
