import { onchainTable } from "@ponder/core";

const provenance = (t: any) => ({ chainId: t.integer().notNull(), blockNumber: t.bigint().notNull(), blockHash: t.text().notNull(), transactionHash: t.text().notNull(), logIndex: t.integer().notNull(), confirmation: t.text().notNull().default("PENDING") });
export const collection = onchainTable("collection", (t) => ({ id: t.text().primaryKey(), creator: t.text().notNull(), implementation: t.text().notNull(), standard: t.integer().notNull(), name: t.text().notNull(), symbol: t.text().notNull(), metadataUri: t.text().notNull(), royaltyRecipient: t.text().notNull(), royaltyBps: t.integer().notNull(), ...provenance(t) }));
export const token = onchainTable("token", (t) => ({ id: t.text().primaryKey(), collectionId: t.text().notNull(), tokenId: t.bigint().notNull(), uri: t.text(), totalSupply: t.bigint().notNull().default(0n), frozen: t.boolean().notNull().default(false), ...provenance(t) }));
export const tokenBalance = onchainTable("token_balance", (t) => ({ id: t.text().primaryKey(), collectionId: t.text().notNull(), tokenId: t.bigint().notNull(), owner: t.text().notNull(), quantity: t.bigint().notNull(), ...provenance(t) }));
export const listing = onchainTable("listing", (t) => ({ id: t.text().primaryKey(), seller: t.text().notNull(), collectionId: t.text().notNull(), tokenId: t.bigint().notNull(), standard: t.integer().notNull(), quantity: t.bigint().notNull(), unitPrice: t.bigint().notNull(), currency: t.text().notNull(), expiresAt: t.bigint(), state: t.integer().notNull(), ...provenance(t) }));
export const purchase = onchainTable("purchase", (t) => ({ id: t.text().primaryKey(), listingId: t.text().notNull(), buyer: t.text().notNull(), quantity: t.bigint().notNull(), saleAmount: t.bigint().notNull(), platformFee: t.bigint().notNull(), royaltyAmount: t.bigint().notNull(), royaltyRecipient: t.text(), currency: t.text().notNull(), ...provenance(t) }));
export const royaltyPayment = onchainTable("royalty_payment", (t) => ({ id: t.text().primaryKey(), purchaseId: t.text().notNull(), recipient: t.text().notNull(), amount: t.bigint().notNull(), currency: t.text().notNull(), ...provenance(t) }));
export const withdrawal = onchainTable("withdrawal", (t) => ({ id: t.text().primaryKey(), payee: t.text().notNull(), currency: t.text().notNull(), amount: t.bigint().notNull(), ...provenance(t) }));
export const governanceAction = onchainTable("governance_action", (t) => ({ id: t.text().primaryKey(), contract: t.text().notNull(), action: t.text().notNull(), actor: t.text().notNull(), data: t.text(), ...provenance(t) }));
export const activity = onchainTable("activity", (t) => ({ id: t.text().primaryKey(), type: t.text().notNull(), collectionId: t.text(), tokenId: t.bigint(), account: t.text(), quantity: t.bigint(), ...provenance(t) }));
export const transactionConfirmation = onchainTable("transaction_confirmation", (t) => ({ id: t.text().primaryKey(), eventType: t.text().notNull(), deduplicationKey: t.text().notNull(), ...provenance(t) }));
export const eventOutbox = onchainTable("event_outbox", (t) => ({ id: t.text().primaryKey(), eventType: t.text().notNull(), payloadVersion: t.integer().notNull(), payload: t.text().notNull(), deduplicationKey: t.text().notNull(), publishedAt: t.bigint(), attempts: t.integer().notNull().default(0), lastError: t.text(), ...provenance(t) }));
