CREATE TYPE "AdminWalletStatus" AS ENUM ('ACTIVE', 'REVOKED');
CREATE TYPE "ModerationTargetType" AS ENUM ('COLLECTION', 'NFT', 'LISTING', 'PROFILE');
CREATE TYPE "ReportCategory" AS ENUM ('SPAM', 'FRAUD', 'COPYRIGHT', 'HARASSMENT', 'OTHER');
CREATE TYPE "ReportStatus" AS ENUM ('OPEN', 'RESOLVED');
CREATE TYPE "ModerationStatus" AS ENUM ('VISIBLE', 'HIDDEN', 'RESOLVED');
CREATE TABLE "AdminWallet" ("id" UUID NOT NULL, "walletId" UUID NOT NULL, "status" "AdminWalletStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "revokedAt" TIMESTAMP(3), CONSTRAINT "AdminWallet_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ModerationSubject" ("id" UUID NOT NULL, "targetType" "ModerationTargetType" NOT NULL, "targetId" VARCHAR(255) NOT NULL, "status" "ModerationStatus" NOT NULL DEFAULT 'VISIBLE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "hiddenAt" TIMESTAMP(3), "resolvedAt" TIMESTAMP(3), CONSTRAINT "ModerationSubject_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserReport" ("id" UUID NOT NULL, "reporterWalletId" UUID NOT NULL, "targetType" "ModerationTargetType" NOT NULL, "targetId" VARCHAR(255) NOT NULL, "category" "ReportCategory" NOT NULL, "description" VARCHAR(2000) NOT NULL, "evidenceUrl" VARCHAR(2048), "status" "ReportStatus" NOT NULL DEFAULT 'OPEN', "resolutionReason" VARCHAR(1000), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), CONSTRAINT "UserReport_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdminAuditLog" ("id" UUID NOT NULL, "actorWalletId" UUID NOT NULL, "action" VARCHAR(64) NOT NULL, "targetType" "ModerationTargetType" NOT NULL, "targetId" VARCHAR(255) NOT NULL, "reason" VARCHAR(1000) NOT NULL, "previousStatus" VARCHAR(32), "newStatus" VARCHAR(32), "requestId" VARCHAR(128), "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdminAuditLog_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "AdminWallet_walletId_key" ON "AdminWallet"("walletId");
CREATE INDEX "AdminWallet_status_createdAt_idx" ON "AdminWallet"("status", "createdAt");
CREATE UNIQUE INDEX "ModerationSubject_targetType_targetId_key" ON "ModerationSubject"("targetType", "targetId");
CREATE INDEX "ModerationSubject_status_targetType_targetId_idx" ON "ModerationSubject"("status", "targetType", "targetId");
CREATE INDEX "UserReport_reporterWalletId_createdAt_idx" ON "UserReport"("reporterWalletId", "createdAt");
CREATE INDEX "UserReport_targetType_targetId_status_createdAt_idx" ON "UserReport"("targetType", "targetId", "status", "createdAt");
CREATE INDEX "AdminAuditLog_actorWalletId_createdAt_idx" ON "AdminAuditLog"("actorWalletId", "createdAt");
CREATE INDEX "AdminAuditLog_targetType_targetId_createdAt_idx" ON "AdminAuditLog"("targetType", "targetId", "createdAt");
CREATE INDEX "AdminAuditLog_action_createdAt_idx" ON "AdminAuditLog"("action", "createdAt");
ALTER TABLE "AdminWallet" ADD CONSTRAINT "AdminWallet_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "WalletProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserReport" ADD CONSTRAINT "UserReport_reporterWalletId_fkey" FOREIGN KEY ("reporterWalletId") REFERENCES "WalletProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserReport" ADD CONSTRAINT "UserReport_targetType_targetId_fkey" FOREIGN KEY ("targetType", "targetId") REFERENCES "ModerationSubject"("targetType", "targetId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AdminAuditLog" ADD CONSTRAINT "AdminAuditLog_actorWalletId_fkey" FOREIGN KEY ("actorWalletId") REFERENCES "WalletProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
