import { ponder } from "ponder:registry";
import { balanceId, eventId } from "@nft-marketplace/database";

const chainId = Number(process.env.PONDER_CHAIN_ID ?? 31337);
const provenance = (event: any, _type: string) => ({ chainId, blockNumber: event.block.number, blockHash: event.block.hash ?? "0x", transactionHash: event.transaction.hash, logIndex: event.log.logIndex, confirmation: "PENDING" });
const recordEvent = async (context: any, event: any, type: string) => { const p = provenance(event, type); await context.db.insert(context.tables.transactionConfirmation).values({ id: eventId(chainId, p.transactionHash, p.logIndex), eventType: type, deduplicationKey: eventId(chainId, p.transactionHash, p.logIndex), ...p }).onConflictDoNothing(); return p; };
const applyBalance = async (context: any, event: any, collectionId: string, tokenId: bigint, owner: string, delta: bigint) => { if (owner.toLowerCase() === "0x0000000000000000000000000000000000000000") return; const id = balanceId(collectionId, tokenId, owner); const current = await context.db.find(context.tables.tokenBalance, { id }); const quantity = BigInt(current?.quantity ?? 0) + delta; const p = provenance(event, "Transfer"); if (current) await context.db.update(context.tables.tokenBalance, { id }).set({ quantity, ...p }); else await context.db.insert(context.tables.tokenBalance).values({ id, collectionId, tokenId, owner, quantity, ...p }).onConflictDoNothing(); };
ponder.on("Factory:CollectionDeployed", async ({ event, context }: any) => { const p = await recordEvent(context, event, "CollectionDeployed"); const id = event.args.collection.toLowerCase(); await context.db.insert(context.tables.collection).values({ id, creator: event.args.creator.toLowerCase(), implementation: event.args.implementation.toLowerCase(), standard: Number(event.args.standard), name: event.args.name, symbol: event.args.symbol, metadataUri: event.args.metadataURI, royaltyRecipient: event.args.royaltyRecipient.toLowerCase(), royaltyBps: Number(event.args.royaltyBps), ...p }).onConflictDoNothing(); });
ponder.on("Settlement:ListingCreated", async ({ event, context }: any) => { const p = await recordEvent(context, event, "ListingCreated"); const id = event.args.listingId.toString(); await context.db.insert(context.tables.listing).values({ id, seller: event.args.seller.toLowerCase(), collectionId: event.args.collection.toLowerCase(), tokenId: event.args.tokenId, standard: Number(event.args.standard), quantity: event.args.quantity, unitPrice: event.args.unitPrice, currency: event.args.currency.toLowerCase(), expiresAt: event.args.expiresAt, state: 0, ...p }).onConflictDoNothing(); });
ponder.on("Settlement:ListingCancelled", async ({ event, context }: any) => { await recordEvent(context, event, "ListingCancelled"); await context.db.update(context.tables.listing, { id: event.args.listingId.toString() }).set({ state: 1 }); });
ponder.on("Settlement:ListingPurchased", async ({ event, context }: any) => { const p = await recordEvent(context, event, "ListingPurchased"); const id = eventId(chainId, event.transaction.hash, event.log.logIndex); const listingId = event.args.listingId.toString(); await context.db.insert(context.tables.purchase).values({ id, listingId, buyer: event.args.buyer.toLowerCase(), quantity: event.args.quantity, saleAmount: event.args.saleAmount, platformFee: event.args.platformFee, royaltyAmount: event.args.royaltyAmount, royaltyRecipient: event.args.royaltyRecipient.toLowerCase(), currency: "0x0000000000000000000000000000000000000000", ...p }).onConflictDoNothing(); await context.db.insert(context.tables.royaltyPayment).values({ id: `${id}:royalty`, purchaseId: id, recipient: event.args.royaltyRecipient.toLowerCase(), amount: event.args.royaltyAmount, currency: "0x0000000000000000000000000000000000000000", ...p }).onConflictDoNothing(); const listing = await context.db.find(context.tables.listing, { id: listingId }); if (listing) { const remaining = BigInt(listing.quantity) - BigInt(event.args.quantity); await context.db.update(context.tables.listing, { id: listingId }).set({ quantity: remaining, state: remaining === 0n ? 2 : listing.state, ...p }); } });
ponder.on("Settlement:PaymentWithdrawn", async ({ event, context }: any) => { const p = await recordEvent(context, event, "PaymentWithdrawn"); const id = eventId(chainId, event.transaction.hash, event.log.logIndex); await context.db.insert(context.tables.withdrawal).values({ id, payee: event.args.payee.toLowerCase(), currency: event.args.currency.toLowerCase(), amount: event.args.amount, ...p }).onConflictDoNothing(); });
ponder.on("Settlement:GovernanceInitialized", async ({ event, context }: any) => { const p = await recordEvent(context, event, "GovernanceInitialized"); const id = eventId(chainId, event.transaction.hash, event.log.logIndex); await context.db.insert(context.tables.governanceAction).values({ id, contract: event.log.address.toLowerCase(), action: "GovernanceInitialized", actor: event.args.multisig.toLowerCase(), data: null, ...p }).onConflictDoNothing(); });
ponder.on("ERC721:Transfer", async ({ event, context }: any) => { const collectionId = event.log.address.toLowerCase(); const tokenId = event.args.tokenId as bigint; await recordEvent(context, event, "Transfer"); await applyBalance(context, event, collectionId, tokenId, event.args.from, -1n); await applyBalance(context, event, collectionId, tokenId, event.args.to, 1n); await context.db.insert(context.tables.activity).values({ id: eventId(chainId, event.transaction.hash, event.log.logIndex), type: "TRANSFER", collectionId, tokenId, account: event.args.to.toLowerCase(), quantity: 1n, ...provenance(event, "Transfer") }).onConflictDoNothing(); });
ponder.on("ERC1155:TransferSingle", async ({ event, context }: any) => { const collectionId = event.log.address.toLowerCase(); const tokenId = event.args.id as bigint; const quantity = event.args.value as bigint; await recordEvent(context, event, "TransferSingle"); await applyBalance(context, event, collectionId, tokenId, event.args.from, -quantity); await applyBalance(context, event, collectionId, tokenId, event.args.to, quantity); });
