import { ponder } from "ponder:registry";

const eventId = (event: { transaction: { hash: string }; log: { logIndex: number } }) => `${event.transaction.hash}-${event.log.logIndex}`;

ponder.on("Factory:CollectionDeployed", async ({ event, context }: any) => {
  const id = event.args.collection.toLowerCase();
  await context.db.insert(context.tables.collection).values({ id, creator: event.args.creator, implementation: event.args.implementation, standard: Number(event.args.standard), name: event.args.name, symbol: event.args.symbol, metadataUri: event.args.metadataURI, royaltyRecipient: event.args.royaltyRecipient, royaltyBps: Number(event.args.royaltyBps), blockNumber: event.block.number, transactionHash: event.transaction.hash, logIndex: event.log.logIndex }).onConflictDoNothing();
});

ponder.on("Settlement:ListingCreated", async ({ event, context }: any) => { const id = event.args.listingId.toString(); await context.db.insert(context.tables.listing).values({ id, seller: event.args.seller, collectionId: event.args.collection.toLowerCase(), tokenId: event.args.tokenId, standard: Number(event.args.standard), quantity: event.args.quantity, unitPrice: event.args.unitPrice, currency: event.args.currency, expiresAt: event.args.expiresAt, state: 0, blockNumber: event.block.number, transactionHash: event.transaction.hash, logIndex: event.log.logIndex }).onConflictDoNothing(); });
ponder.on("Settlement:ListingCancelled", async ({ event, context }: any) => { await context.db.update(context.tables.listing, { id: event.args.listingId.toString() }).set({ state: 1 }); });
ponder.on("Settlement:ListingPurchased", async ({ event, context }: any) => { const id = eventId(event); await context.db.insert(context.tables.purchase).values({ id, listingId: event.args.listingId.toString(), buyer: event.args.buyer, quantity: event.args.quantity, saleAmount: event.args.saleAmount, platformFee: event.args.platformFee, royaltyAmount: event.args.royaltyAmount, royaltyRecipient: event.args.royaltyRecipient, currency: "0x0000000000000000000000000000000000000000", blockNumber: event.block.number, transactionHash: event.transaction.hash, logIndex: event.log.logIndex }).onConflictDoNothing(); });
ponder.on("Settlement:PaymentWithdrawn", async ({ event, context }: any) => { const id = eventId(event); await context.db.insert(context.tables.withdrawal).values({ id, payee: event.args.payee, currency: event.args.currency, amount: event.args.amount, blockNumber: event.block.number, transactionHash: event.transaction.hash, logIndex: event.log.logIndex }).onConflictDoNothing(); });
ponder.on("Settlement:GovernanceInitialized", async ({ event, context }: any) => { const id = eventId(event); await context.db.insert(context.tables.governanceAction).values({ id, contract: event.log.address, action: "GovernanceInitialized", actor: event.args.multisig, data: null, blockNumber: event.block.number, transactionHash: event.transaction.hash, logIndex: event.log.logIndex }).onConflictDoNothing(); });
