import React from 'react';
const h = React.createElement;
export const WalletState = Object.freeze({ DISCONNECTED: 'disconnected', CONNECTING: 'connecting', CONNECTED: 'connected', WRONG_NETWORK: 'wrong-network', REJECTED: 'rejected', SIGNING: 'signing' });
export const TransactionState = Object.freeze({ INTENT: 'intent', PENDING: 'pending', SUBMITTED: 'submitted', CONFIRMED: 'confirmed', FAILED: 'failed', EXPIRED: 'expired' });
export function Button({ variant = 'primary', children, ...props }) { return h('button', { className: 'nft-button', 'data-variant': variant, ...props }, children); }
export function Stack({ children, ...props }) { return h('div', { className: 'nft-stack', ...props }, children); }
export function Grid({ children, ...props }) { return h('div', { className: 'nft-grid', ...props }, children); }
export function Field({ label, error, id, children }) { return h('label', { className: 'nft-ui nft-stack', htmlFor: id }, h('span', null, label), children, error ? h('span', { className: 'nft-status', 'data-tone': 'danger', role: 'alert' }, error) : null); }
export function Input(props) { return h('input', { className: 'nft-input', ...props }); }
export function Select(props) { return h('select', { className: 'nft-select', ...props }); }
export function Form({ children, onSubmit, ...props }) { return h('form', { className: 'nft-ui nft-stack', onSubmit, ...props }, children); }
export function Table({ columns, rows, getRowKey = (_, index) => index }) { return h('div', { role: 'region', 'aria-label': 'Data table', style: { overflowX: 'auto' } }, h('table', { className: 'nft-ui' }, h('thead', null, h('tr', null, columns.map((column) => h('th', { key: column.key, scope: 'col' }, column.label)))), h('tbody', null, rows.map((row, index) => h('tr', { key: getRowKey(row, index) }, columns.map((column) => h('td', { key: column.key }, column.render ? column.render(row) : row[column.key]))))))); }
export function Gallery({ items, renderItem, getKey = (item) => item.id }) { return h('div', { className: 'nft-grid', 'aria-label': 'Gallery' }, items.map((item) => h('article', { className: 'nft-card', key: getKey(item) }, renderItem(item)))); }
export function Card({ title, children }) { return h('section', { className: 'nft-card' }, h('div', { className: 'nft-card__body' }, h('h3', null, title), children)); }
export function WalletStatus({ state, onAction }) { const labels = { [WalletState.DISCONNECTED]: 'Connect wallet', [WalletState.CONNECTING]: 'Connecting wallet', [WalletState.CONNECTED]: 'Wallet connected', [WalletState.WRONG_NETWORK]: 'Switch network', [WalletState.REJECTED]: 'Connection rejected', [WalletState.SIGNING]: 'Confirm signature' }; const actionable = [WalletState.DISCONNECTED, WalletState.WRONG_NETWORK, WalletState.REJECTED].includes(state); return h('div', { className: 'nft-ui', role: 'status', 'aria-live': 'polite' }, h('span', null, labels[state] ?? 'Wallet unavailable'), actionable ? h(Button, { onClick: onAction }, labels[state]) : null); }
export function TransactionStatus({ state, error }) { const labels = { [TransactionState.INTENT]: 'Transaction ready', [TransactionState.PENDING]: 'Waiting for wallet', [TransactionState.SUBMITTED]: 'Transaction submitted', [TransactionState.CONFIRMED]: 'Transaction confirmed', [TransactionState.FAILED]: 'Transaction failed', [TransactionState.EXPIRED]: 'Transaction expired' }; return h('div', { className: 'nft-ui nft-status', 'data-tone': state === TransactionState.FAILED ? 'danger' : 'neutral', role: 'status', 'aria-live': 'polite' }, h('strong', null, labels[state] ?? 'Transaction status unavailable'), error ? h('span', { role: 'alert' }, error) : null); }
export function Responsive({ children, as: Element = 'div', ...props }) { return h(Element, { className: 'nft-ui', ...props }, children); }
