export const ErrorCode = Object.freeze({
  VALIDATION: 'VALIDATION_ERROR',
  AUTHENTICATION: 'AUTHENTICATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  INTERNAL: 'INTERNAL_ERROR',
  SIWE_INVALID_DOMAIN: 'SIWE_INVALID_DOMAIN',
  SIWE_INVALID_CHAIN: 'SIWE_INVALID_CHAIN',
  SIWE_INVALID_NONCE: 'SIWE_INVALID_NONCE',
  SIWE_INVALID_SIGNATURE: 'SIWE_INVALID_SIGNATURE',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  REFRESH_REUSE: 'REFRESH_TOKEN_REUSE',
  SCOPE_DENIED: 'SCOPE_DENIED',
  CHAIN_OWNERSHIP: 'CHAIN_OWNERSHIP_ERROR',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',
  STALE_STATE: 'STALE_STATE',
  INVALID_TRANSACTION_INTENT: 'INVALID_TRANSACTION_INTENT',
  COLLECTION_ACCESS: 'COLLECTION_ACCESS_ERROR',
  METADATA_FROZEN: 'METADATA_FROZEN',
  LISTING_EXPIRED: 'LISTING_EXPIRED',
  INVALID_LISTING_STATE: 'INVALID_LISTING_STATE',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  PRIVACY_ERASURE_COMPLETE: 'PRIVACY_ERASURE_COMPLETE',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
});

export class AppError extends Error {
  constructor(code, message, options = {}) {
    super(message, { cause: options.cause });
    this.name = 'AppError';
    this.code = code;
    this.details = options.details;
    this.retryable = options.retryable ?? false;
  }
  toJSON() {
    return {
      code: this.code,
      message: this.message,
      details: this.details,
      retryable: this.retryable,
    };
  }
}
